using Volo.Abp;

namespace Abp.ContributorPatternExample.EntityFrameworkCore;

public abstract class ContributorPatternExampleEntityFrameworkCoreTestBase : ContributorPatternExampleTestBase<ContributorPatternExampleEntityFrameworkCoreTestModule>
{

}
