using Abp.ContributorPatternExample.EntityFrameworkCore;

namespace Abp.ContributorPatternExample;

public class ContributorPatternExampleWebCollection : ContributorPatternExampleEntityFrameworkCoreCollectionFixtureBase
{

}
